### ISSUE TITLE
Water tile upgrades

### ISSUE THREAD

**Issue by Afganitia** [Gafaszt2/Ark-s-UNCIV-Evolved#1]
While playing this mod, I realize that there is no way to make water tile upgrades like fishing boats. There are no work boats, and workers cannot do them. I don't see any unit capable of doing this upgrades.
Is this intended?

PD: I would also check the "regular lands" building conditions. I should be able to build one, but I can't.

**Comment by Gafaszt2** [comment]
Dont worry i will make the work boats as soon as i can :)
